apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thesis-simple-dev
  namespace: argocd
  annotations:
    # Annotation cho biết đây là môi trường DEV
    environment: dev
    auto-sync: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/o0akin0o/gitops-thesis-demo.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true